### ISSUE TITLE
ReadPublicIpRanges for two regions same return

### ISSUE THREAD

**Issue by ihaz** [outscale/oapi-cli#13]
Hello,

`oapi-cli-x86_64.AppImage --profile=cloudgouv-eu-west-1 ReadPublicIpRanges
"RequestId":"3a231551-b338-40ca-8462-db847677d73f"`

`oapi-cli-x86_64.AppImage --profile=eu-west-2 ReadPublicIpRanges
"RequestId":"49986c8a-1cd5-48a5-87b5-924a300c29e2"`

seems to have a bad return with sec-1, no consideration of the profile i think

Regards

**Comment by ihaz** [comment]
We need to use `export OSC_REGION=cloudgouv-eu-west-1` the region in profile file is not used

**Comment by outscale-mgo** [comment]
it seems, the error was due to using `region_name` instead of `region` in config file.
can we close this as won't do ?

**Comment by ihaz** [comment]
Ok thanks 👍
