### ISSUE TITLE
CreateSnapshot command can not parse SnapshotSize parameter if greater than 2Gb

### ISSUE THREAD

**Issue by oleastre** [outscale/oapi-cli#67]
I'm trying to create a snapshot from a pre-signed bucket URL.

When running in verbose mode, if I set the `SnapshotSize` parameter to more than 2147483647 I get either negative sizes or no value at all.
It seems you are using a 16bits parsing while snapshot sizes should probably be encoded as 32bit int. 

The old osc-cli and the cockpit interfaces do not have that restriction and happily parse bigger values. My target value was 8Gb = 8589934592 bytes.

**Comment by outscale-mgo** [comment]
Hello,
thanks for reporting the issue.
I'm using int, which are 32 bit, but signed, so they overflow after 2 GB.
Anyway, I'm changing them to long long int asap.

**Comment by oleastre** [comment]
Indeed it was signed 32 bits and not 16 bits I was a bit confused.
I just tested the snapshot build and it works as expected. Thanks for the quick fix!
